import { HardeningConfig, Distro } from '../types';
import { HARDENING_OPTIONS } from '../constants';

export function generateHardeningScript(config: HardeningConfig): string {
  const { distro, options, customPort = 22, newUsername, isSudo, syslogServer = 'logs.example.com' } = config;
  
  let script = `#!/bin/bash
# VPS Hardening Script generated by HardenedVPS
# Target Distro: ${distro}
# Date: ${new Date().toISOString()}

set -e

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
  echo "Please run as root"
  exit 1
fi

echo "Starting VPS hardening process for ${distro}..."

# --- Helper Functions ---
backup_file() {
  local file=$1
  if [ -f "$file" ]; then
    local backup_name="\${file}.bak.$(date +%F_%H-%M-%S)"
    cp -p "$file" "$backup_name"
    echo "Backed up $file to $backup_name"
  fi
}

set_config() {
  local file=$1
  local key=$2
  local value=$3
  local separator=\${4:-" "}
  
  if [ ! -f "$file" ]; then
    touch "$file"
  fi
  
  # Check if the key exists (commented or uncommented)
  if grep -qE "^[#\\s]*\${key}[\\s=]+" "$file"; then
    # Replace the existing line
    sed -i -E "s/^[#\\s]*\${key}[\\s=]+.*/\${key}\${separator}\${value}/" "$file"
  else
    # Append to the end of the file
    echo "\${key}\${separator}\${value}" >> "$file"
  fi
}

# Backup critical configurations before modifying
echo "Backing up critical configurations..."
backup_file "/etc/ssh/sshd_config"
backup_file "/etc/sysctl.conf"
backup_file "/etc/audit/auditd.conf"
backup_file "/etc/default/ufw"

# Update package lists
`;

  if (['ubuntu', 'debian'].includes(distro)) {
    script += 'apt-get update\n';
  } else if (['centos', 'rhel', 'fedora'].includes(distro)) {
    script += 'yum update -y\n';
  }

  // Handle New User Creation if Root Login is disabled
  if (options['ssh_root_login'] && newUsername) {
    script += `\n# --- Create New Administrative User ---\necho "Creating user: ${newUsername}..."\n`;
    script += `if ! id "${newUsername}" &>/dev/null; then\n`;
    script += `  useradd -m -s /bin/bash "${newUsername}"\n`;
    script += `  echo "Please set a password for ${newUsername}:"\n`;
    script += `  passwd "${newUsername}"\n`;
    
    if (isSudo) {
      if (['ubuntu', 'debian'].includes(distro)) {
        script += `  usermod -aG sudo "${newUsername}"\n`;
      } else {
        script += `  usermod -aG wheel "${newUsername}"\n`;
      }
      script += `  echo "User ${newUsername} added to sudo/wheel group."\n`;
    }
    script += `else\n`;
    script += `  echo "User ${newUsername} already exists."\n`;
    script += `fi\n`;
  }

  HARDENING_OPTIONS.forEach(option => {
    if (options[option.id]) {
      script += `\n# --- ${option.label} ---\necho "Applying: ${option.label}..."\n`;
      
      let snippet = option.scripts[distro] || option.scripts.generic;
      
      if (snippet) {
        // Replace placeholders
        snippet = snippet.replace(/{{SSH_PORT}}/g, customPort.toString());
        snippet = snippet.replace(/{{SYSLOG_SERVER}}/g, syslogServer);
        script += snippet + '\n';
      } else {
        script += `# No specific script for ${distro}, skipping...\n`;
      }
    }
  });

  script += `
# Validate and Restart SSH service
echo "Validating SSH configuration..."
if sshd -t; then
  echo "SSH configuration is valid. Restarting SSH service..."
  systemctl restart ssh || systemctl restart sshd
else
  echo "ERROR: SSH configuration validation failed!"
  echo "Please check /etc/ssh/sshd_config and restore from backup if necessary."
  echo "Hardening script aborted to prevent locking you out."
  exit 1
fi

echo "--------------------------------------------------"
echo "Hardening complete!"
echo "IMPORTANT: If you changed the SSH port to ${customPort}, make sure to use it for your next login."
echo "Example: ssh -p ${customPort} user@your_vps_ip"
echo "--------------------------------------------------"
`;

  return script;
}
