import { HardeningConfig, Distro } from '../types';
import { HARDENING_OPTIONS } from '../constants';

export function generateHardeningScript(config: HardeningConfig): string {
  const { distro, options, customPort = 22, newUsername, isSudo, syslogServer = 'logs.example.com' } = config;
  
  let script = `#!/bin/bash
# VPS Hardening Script generated by HardenedVPS
# Target Distro: ${distro}
# Date: ${new Date().toISOString()}

set -e

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
  echo "Please run as root"
  exit 1
fi

echo "Starting VPS hardening process for ${distro}..."

# Update package lists
`;

  if (['ubuntu', 'debian'].includes(distro)) {
    script += 'apt-get update\n';
  } else if (['centos', 'rhel', 'fedora'].includes(distro)) {
    script += 'yum update -y\n';
  }

  // Handle New User Creation if Root Login is disabled
  if (options['ssh_root_login'] && newUsername) {
    script += `\n# --- Create New Administrative User ---\necho "Creating user: ${newUsername}..."\n`;
    script += `if ! id "${newUsername}" &>/dev/null; then\n`;
    script += `  useradd -m -s /bin/bash "${newUsername}"\n`;
    script += `  echo "Please set a password for ${newUsername}:"\n`;
    script += `  passwd "${newUsername}"\n`;
    
    if (isSudo) {
      if (['ubuntu', 'debian'].includes(distro)) {
        script += `  usermod -aG sudo "${newUsername}"\n`;
      } else {
        script += `  usermod -aG wheel "${newUsername}"\n`;
      }
      script += `  echo "User ${newUsername} added to sudo/wheel group."\n`;
    }
    script += `else\n`;
    script += `  echo "User ${newUsername} already exists."\n`;
    script += `fi\n`;
  }

  HARDENING_OPTIONS.forEach(option => {
    if (options[option.id]) {
      script += `\n# --- ${option.label} ---\necho "Applying: ${option.label}..."\n`;
      
      let snippet = option.scripts[distro] || option.scripts.generic;
      
      if (snippet) {
        // Replace placeholders
        snippet = snippet.replace(/{{SSH_PORT}}/g, customPort.toString());
        snippet = snippet.replace(/{{SYSLOG_SERVER}}/g, syslogServer);
        script += snippet + '\n';
      } else {
        script += `# No specific script for ${distro}, skipping...\n`;
      }
    }
  });

  script += `
# Restart SSH service to apply changes
echo "Restarting SSH service..."
systemctl restart ssh || systemctl restart sshd

echo "--------------------------------------------------"
echo "Hardening complete!"
echo "IMPORTANT: If you changed the SSH port to ${customPort}, make sure to use it for your next login."
echo "Example: ssh -p ${customPort} user@your_vps_ip"
echo "--------------------------------------------------"
`;

  return script;
}
